name: Hello
author: Abdelhameed Ghazy
flag: idek{Ghazy_N3gm_Elbalad}
description: Just to warm you up for the next Fight :"D \n Note: the admin bot is not on the same machine as the challenge itself and the *.chal.idek.team:1337 URL should be used for the admin bot URL
