name: Yaoguai Bank
author: Osama Ali
flag: YAO{b4nk_s3cur1ty_writt3n_by_1nt3rn}
description: "E-Corp is up to no good again.\nThey just opened a new bank, and we found out they’re stealing money from people!\nAs part of Yaoguai, it’s our job to stop them and bring justice.\nWe got our hands on their source code - take a look and see what you can find."