name: Y40Inc1d3n7_C2
author: 0xS1rx58
flag: YAO{B0T_53rv3R-1_PWN3D_BY_C2@2121}
description: "During the investigation, a suspicious TCP connection was detected.\nYour task is to analyze the traffic and uncover the nature of the C2 activity."